import jwt from 'jsonwebtoken';
import uuid from 'node-uuid';
const uuidV4 = require('uuid');

export const secret = 'lukeiamyourfather'; 
export const exercises_core_pack = "["+
//CORE BEGINS
									'{ VideoURL:"https://www.youtube.com/watch?v=Q9AlsWFyYE8&feature=youtu.be", location: ["gym", "home"], levels: ["superset", "low"], gender: ["male", "female"], name: "Plank", sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "Your Hips must not sag. Fight to keep hips in line with the rest of your body. Try putting a PVC pipe or broomstick on your back next time you do a plank. It should touch the top of your tailbone, your upper back and the back of your head. That is  how you know you are in a neutral position and performing them correctly.", part:"core", detailed_part: "abs" }, '+	
									'{ VideoURL:"https://youtu.be/N8xOZ9cHHjo", location: ["gym", "home"], levels: ["superset", "low"], gender: ["male", "female"], name: "Crunch", sets: '+"'" + ' { "superset": [ { "reps": "30", "rest" : "0" } ], "low": [ { "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "Do not jerk your weight up. Focus on utilizing your abs to raise your body up and make sure you are moving slowly and deliberately as you perform each crunch. Do not perform a sit up and instead focus on cruching your abs. Do not focus on raising all the way up as you would for a sit up.", part:"core", detailed_part: "abs" }, '+
									'{ VideoURL:"https://youtu.be/Ot2x2yhV1f0", location: ["gym", "home"], levels: ["superset", "low"], gender: ["male", "female"], name: "Sit up", sets: '+"'" +' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ { , "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: " ", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/AFBC0HDflWo", name: "Air Bicycle", location: ["gym", "home"], levels: ["superset", "low"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: " ", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/ZF_fwwd5oxw", name: "Lying Leg Raise", location: ["gym", "home"], levels: ["superset", "low"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+  
									'{ VideoURL:"https://youtu.be/_LiAqnFE5mg", name: "Ab Plate Twist", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets:'+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "medium": [{  "reps": "30", "rest" : "30" }, {  "reps": "30", "rest" : "30" }, {  "reps": "30", "rest" : "30"}, {  "reps": "30", "rest" : "45"}], "high": [{  "reps": "30", "rest" : "30" }, {  "reps": "30", "rest" : "30" }, {  "reps": "30", "rest" : "30"}, {  "reps": "30", "rest" : "45"}, {  "reps": "30", "rest" : "45"}] }'+"'" +', uuid: '+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+ 
									'{ VideoURL:"https://youtu.be/G1Xpt8vbVBc", name: "Mountain Climber", location: ["gym", "home"], levels: ["superset", "low"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/VAERCnrM_l8", name: "Full Hanging Leg Raise", location: ["gym"], levels: ["superset", "low", "medium"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/KNgfBz_u9LU", name: "Machine Ab Crunch", location: ["gym"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/tKIygTzTLmM", name: "Reverse Crunch", location: ["gym"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/m1HFK3Wdt0U", name: "Elbow to Knee Cross Touch", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/v30TIy18LEo", name: "Pulse Up", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/U9wAK2bgY2E", name: "Ab Roller", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/9yiWAgm3DSU", name: "Pilates Burpee", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/UYIyr1TRJaw", name: "Scissor Kick", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/4QnjuZbjvSY", name: "Cable Crunch", location: ["gym"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/CK3BRfEgsOA", name: "Roman Chair Leg Raise", location: ["gym"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/2h5HU6ug8ik", name: "Vertical Leg Crunch", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/2R05oeCl2qQ", name: "Swiss Ball Crunch", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets:'+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/nsYFSwxEPxM", name: "Flat Bench Lying Leg Raise", location: ["gym"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/_433swsNPaM", name: "Tuck Crunch", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/H7KsymxoCc0", name: "Dead Bug", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/uQ83N79iHXs", name: "Double Crunch", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/zlnBSufRW-o", name: "Weighted Sit-Up", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/EfLwc7Y9m08", name: "Weighted Decline Sit-Up", location: ["gym"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/FfZuwZAvGkQ", name: "Swiss Ball Ab Rollout", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/K7InUqXlExw", name: "Up Up Down Down Elbow Push-Up", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/SzT-4AtOCo8", name: "Pilates Rollups", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/a7ZnLpLIb8s", name: "Medicine Ball Slam", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/V1bLfMetLvc", name: "Roman Chair Knee Raise", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/RB8AuO2svV0", name: "Decline Crunch", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+ 
									'{ VideoURL:"https://youtu.be/JE5ckyDECqc", name: "Weighted Crunch", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/w07_mQSjHzM", name: "Barbell Floor Wiper", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/7iMHiIt8-4o", name: "V-Up", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/WndfVYFm0bM", name: "Plank w/ Ball Rollout", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/xIRZXPKnvU8", name: "Swiss Ball Pike", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/R3TBHUOMs1M", name: "360 Degree Hanging Leg Rotation", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/6yYagCoInrA", name: "Medicine Ball V-Up", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/6sDst0UB_ig", name: "Flat Bench Reverse Ab Crunch", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets:'+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/ug3DPR_y9YE", name: "Sit-Up Twist", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/O6JpvjmhmJM", name: "Kettlebell Figure 8", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/VQnFDVErAUI", name: "Core Rapid Through the Legs", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/C7bR2UIRxQ8", name: "Bench Knee Pull-In", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/HVe7pB-wGSk", name: "Heel Touch", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/T1FhnJn2KIs", name: "Barbell Ab Rollout", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/DX6xDjNnra4", name: "Teaser", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/KjpRk4VNJiQ", name: "Barbell Torque", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/J1ojfoUdDs0", name: "360-Degree Lying Leg Rotation", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/IwzqjMdZviA", name: "Single-Leg Drop", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
									'{ VideoURL:"https://youtu.be/Hlqbf9vZXy4", name: "Single-Leg Jackknife", location: ["gym", "home"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], sets: '+"'" + ' { "superset": [ {  "reps": "30", "rest" : "0"  } ], "low": [ {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45" }, {  "reps": "30", "rest" : "45"} ], "high": [ {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30" }, {  "reps": "50", "rest" : "30"} ] }'+"'" +', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"core", detailed_part: "abs"}, '+
//END OF CORE
//
//BEGINNING BACK
									'{ VideoURL:"https://www.youtube.com/watch?v=KoYm_DZf-LA&feature=youtu.be", location: ["gym"], levels: ["superset", "medium","high"], gender: ["male", "female"], name: "Bent-Over Barbell Row", sets: '+"'"+ ' { "superset": [ {  "reps": "12", "rest" : "0"  } ], "medium": [ {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45"}, {  "reps": "10", "rest" : "45"} ], "high": [ {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "8", "rest" : "45"}, {  "reps": "10", "rest" : "45"}, {  "reps": "15", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description:" Hold onto a barbell with your palms facing down. Bend your knees slightly and bend forward at the waist while keeping your back straight. It should be almost parallel with the floor. The barbell should be directly in front of you; your arms should be perpendicular to the floor. This is the starting position. While keeping your torso stationary, lift the barbell toward you. Your elbows should be kept close to your body. Use only your forearms to hold the weight. When you get to the top, squeeze your back muscles and hold for a few seconds.", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=Q-d1aRlQ8gk&feature=youtu.be", location: ["gym"], levels: ["superset", "low", "medium"], gender: ["male", "female"], name: "Machine Reverse Fly", sets: '+"'"+ ' { "superset": [ {  "reps": "12", "rest" : "0"  } ], "low": [ {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "8", "rest" : "45"}, {  "reps": "15", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=iq8eW1duhRk&feature=youtu.be", location: ["gym", "home"], levels: ["superset", "low"], gender: ["male", "female"], name: "Lying Bird Dog", sets: '+"'"+ ' { "superset": [ {  "reps": "12", "rest" : "0"  } ], "low": [ {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=AoLpLTm2Jgc&feature=youtu.be", location: ["gym"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], name: "T-Bar Row", sets: '+"'"+ ' { "superset": [ {  "reps": "12", "rest" : "0"  } ], "low": [ {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45"} ], "medium": [ {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45"}, {  "reps": "10", "rest" : "45"} ] , "high": [ {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45"}, {  "reps": "10", "rest" : "45"}, {  "reps": "10", "rest" : "45"}, {  "reps": "15", "rest" : "45"} ]}'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "Keep a natural arch in your lower back and chest up and out. Pull the weight to your chest, so that your shoulder blades pinch together at the top", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=JLWVrs1o7fk&feature=youtu.be", location: ["gym", "home"], levels: ["superset", "low", "medium"], gender: ["male", "female"], name: "Wide-Grip Pull-Up", sets: '+"'"+ ' { "superset": [ {  "reps": "12", "rest" : "0"  } ], "low": [ {  "reps": "20", "rest" : "45" }, {  "reps": "20", "rest" : "45" }, {  "reps": "20", "rest" : "45"} ], "medium": [ {  "reps": "20", "rest" : "45" }, {  "reps": "20", "rest" : "45" }, {  "reps": "20", "rest" : "45"}, {  "reps": "20", "rest" : "45"}, {  "reps": "20", "rest" : "45"}, {  "reps": "20", "rest" : "45"}, {  "reps": "20", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "mid-back" }, '+ 
									'{ VideoURL:"https://www.youtube.com/watch?v=lMBKFUfJw9o&feature=youtu.be", location: ["gym"], levels: ["superset", "low", "medium", "high"], gender: ["male", "female"], name: "Reverse-Grip Bent-Over Row", sets: '+"'"+ ' { "superset": [ {  "reps": "12", "rest" : "0"  } ], "low": [ {  "reps": "20", "rest" : "45" }, {  "reps": "20", "rest" : "45" }, {  "reps": "20", "rest" : "45"} ], "medium": [ {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45"}, {  "reps": "14", "rest" : "45"} ], "high": [ {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45"}, {  "reps": "10", "rest" : "45"}, {  "reps": "8", "rest" : "45"}, {  "reps": "15", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "Stand behind a barbell with your feet shoulder width apart. Bend your knees and bend your torso forward to grasp the barbell with your palms facing up (supinated). Raise the barbell slightly so that your arms are fully extended and the barbell is close to your knees. Your back should still be straight but nearly parallel to the floor for this starting position. Keeping your body stationary, exhale as you use only your arms to lift the barbell by bending your elbows straight backward. The barbell should be close to your waist", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=PquZHA_Ft3s&feature=youtu.be", location: ["gym"], levels: ["superset", "low", "medium"], gender: ["male", "female"], name: "One-Arm Cable Row", sets: '+"'"+ ' { "superset": [ {  "reps": "12", "rest" : "0"  } ], "low": [ {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45"} ], "medium": [ {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45"}, {  "reps": "14", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "Grab the stirrup handle in your right hand with an overhand grip. Sit up straight with arm out in front. This is the starting position.", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=PquZHA_Ft3s&feature=youtu.be", location: ["gym", "home"], levels: ["low"], gender: ["male", "female"], name: "TRX Inverted Row", sets: '+"'"+ ' {  "low": [ {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "The trx inverted row is a alternative and calisthenics exercise that primarily targets the middle back and to a lesser degree also targets the biceps, forearms, lower back and shoulders.", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=DZ-s7bxVy1w&feature=youtu.be", location: ["gym"], levels: ["superset","low", "medium"], gender: ["male", "female"], name: "Incline Dumbbell Row", sets: '+"'"+ ' { "superset": [ {  "reps": "12", "rest" : "0"  } ], "low": [ {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45"} ], "medium": [ {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "The incline dumbbell row is a free weights exercise that primarily targets the middle back and to a lesser degree also targets the biceps, lats and traps. Grab a dumbbell in each hand and rotate your hands so your palms are facing each other.", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=98VnvfOPLIc&feature=youtu.be", location: ["gym"], levels: ["superset","low", "medium", "high"], gender: ["male", "female"], name: "Barbell Rear Delt Row", sets: '+"'"+ ' { "superset": [ {  "reps": "12", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45"} ], "medium": [ {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"} ], "high": [ {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"}, {  "reps": "10", "rest" : "45"}, {  "reps": "12", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "The barbell rear delt row is a free weights exercise that primarily targets the middle back and to a lesser degree also targets the biceps, shoulders and traps. With slightly bent knees bend over at the waist so that your chest is parallel with the floor.", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=De7Ejrxo7Zs&feature=youtu.be", location: ["gym"], levels: ["superset","low", "medium"], gender: ["male", "female"], name: "Alternating Bent-Over Row", sets: '+"'"+ ' { "superset": [ {  "reps": "12", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45"} ], "medium": [ {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "The barbell rear delt row is a free weights exercise that primarily targets the middle back and to a lesser degree also targets the biceps, shoulders and traps. With slightly bent knees bend over at the waist so that your chest is parallel with the floor.", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=QWsHaMO86OY&feature=youtu.be", location: ["gym"], levels: ["superset","low", "medium", "high"], gender: ["male", "female"], name: "Lying Cambered Row", sets: '+"'"+ ' { "superset": [ {  "reps": "12", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45"} ], "medium": [ {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"} ], "high": [ {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "The lying cambered row is a free weights exercise that primarily targets the middle back and to a lesser degree also targets the traps, biceps and lats. Lie down on the exercise bench and grab the bar using a palms-down grip. Your hands should be wider than shoulder width apart. This is the starting position", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=52aG_gcxsfA&feature=youtu.be", location: ["gym"], levels: ["superset","low"], gender: ["male", "female"], name: "Standing Rope Cable Row", sets: '+"'"+' { "superset": [ {  "reps": "12", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "The standing rope cable row is a exercise machine exercise that primarily targets the middle back and to a lesser degree also targets the biceps, forearms, lats, lower back and shoulders. Pull the rope into your midsection right below your chest. As you pull the rope in spread the handles as wide as you can.", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=4B7xq7mX4X0&feature=youtu.be", location: ["gym", "home"], levels: ["superset","low", "medium","high"], gender: ["male", "female"], name: "Resistance Band Reverse Fly", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45"} ], "medium": [ {  "reps": "15", "rest" : "35" }, {  "reps": "15", "rest" : "35" }, {  "reps": "12", "rest" : "35"}, {  "reps": "12", "rest" : "45"} ], "high": [ {  "reps": "15", "rest" : "35" }, {  "reps": "15", "rest" : "35" }, {  "reps": "12", "rest" : "35"}, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "35"}, {  "reps": "12", "rest" : "35"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "The standing rope cable row is a exercise machine exercise that primarily targets the middle back and to a lesser degree also targets the biceps, forearms, lats, lower back and shoulders. Pull the rope into your midsection right below your chest. As you pull the rope in spread the handles as wide as you can.", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=J6danxDrQzU", location: ["gym", "home"], levels: ["superset","low", "medium"], gender: ["male", "female"], name: "Kroc Row", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45"} ], "medium": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "The kroc row is a free weights exercise that primarily targets the middle back and to a lesser degree also targets the biceps, forearms, lats, lower back, shoulders and traps. Place your left knee and left hand on the bench, use your right leg to help stabilize you on the ground.", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=XCXSEmW7rwk&feature=youtu.be", location: ["gym"], levels: ["superset","low", "medium", "high"], gender: ["male", "female"], name: "Seated Straight-Bar Cable Row", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45"} ], "medium": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"} ], "high": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=Uj19fFUMbIs&feature=youtu.be", location: ["gym"], levels: ["superset","low", "medium", "high"], gender: ["male", "female"], name: "Seated Underhand-Grip Cable Row", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45"} ], "medium": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"} ], "high": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=AY4YjAHcWrw&feature=youtu.be", location: ["gym"], levels: ["superset","low", "medium", "high"], gender: ["male", "female"], name: "Meadows Row", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45"} ], "medium": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"} ], "high": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=4sRASVJyfWg&feature=youtu.be", location: ["gym", "home"], levels: ["superset","low", "medium"], gender: ["male", "female"], name: "Resistance Band Seated Rear Delt Row", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "25", "rest" : "45" }, {  "reps": "20", "rest" : "45" }, {  "reps": "15", "rest" : "45"} ], "medium": [ {  "reps": "20", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "20", "rest" : "45"}, {  "reps": "18", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=JX03ED-DNPE", location: ["gym"], levels: ["superset","low", "medium", "high"], gender: ["male", "female"], name: "Parallel Grip Lat Pulldown", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "60" }, {  "reps": "15", "rest" : "60" } ], "medium": [ {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "12", "rest" : "45"} ], "high": [ {  "reps": "12", "rest" : "30" }, {  "reps": "10", "rest" : "45" }, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "60"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=lueEJGjTuPQ", location: ["gym"], levels: ["superset","low", "medium", "high"], gender: ["male", "female"], name: "Wide-Grip Lat Pulldown", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "60" }, {  "reps": "15", "rest" : "60" } ], "medium": [ {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "12", "rest" : "45"} ], "high": [ {  "reps": "12", "rest" : "30" }, {  "reps": "10", "rest" : "45" }, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "60"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=apzFTbsm7HU", location: ["gym"], levels: ["superset","low", "medium", "high"], gender: ["male", "female"], name: "Reverse Lat Pulldown", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "60" }, {  "reps": "15", "rest" : "60" } ], "medium": [ {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "12", "rest" : "45"} ], "high": [ {  "reps": "12", "rest" : "30" }, {  "reps": "10", "rest" : "45" }, {  "reps": "12", "rest" : "45"}, {  "reps": "12", "rest" : "60"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=ttvfGg9d76c", location: ["gym"], levels: ["superset","low", "medium" ], gender: ["male", "female"], name: "Dumbbell Bent-Over Raise", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "60" }, {  "reps": "15", "rest" : "60" } ], "medium": [ {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "12", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=GZbfZ033f74", location: ["gym"], levels: ["superset","low", "medium" ], gender: ["male", "female"], name: "Seated Low Row (LF Cable)", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "60" }, {  "reps": "15", "rest" : "60" } ], "medium": [ {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "12", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=j9iPqtJm440&feature=youtu.be", location: ["gym"], levels: ["superset","low", "medium" ], gender: ["male", "female"], name: "One-Arm Half-Kneeling Cable Row", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "60" }, {  "reps": "15", "rest" : "60" }, {  "reps": "15", "rest" : "60" } ], "medium": [ {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "12", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=B5jova9vdXU&feature=youtu.be", location: ["gym"], levels: ["superset","low", "medium" ], gender: ["male", "female"], name: "X Pulldown", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "60" }, {  "reps": "15", "rest" : "60" }, {  "reps": "15", "rest" : "60" } ], "medium": [ {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "12", "rest" : "45"} ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "mid-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=kpWSFmQOz10", location: ["gym"], levels: ["superset","low" ], gender: ["male", "female"], name: "Lower Back Machine", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" } ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "low-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=FQKfr1YDhEk", location: ["gym", "home"], levels: ["superset","low", "medium", "high" ], gender: ["male", "female"], name: "Dumbbell Romainian Deadlift", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" } ], "medium": [ {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "45" } ], "high": [ {  "reps": "12", "rest" : "35" }, {  "reps": "12", "rest" : "35" }, {  "reps": "10", "rest" : "60" }, {  "reps": "10", "rest" : "45" }, {  "reps": "10", "rest" : "100" } ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "low-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=IWRM3eC2GT0", location: ["gym", "home"], levels: ["superset","low" ], gender: ["male", "female"], name: "Swiss Ball Back Extension", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" }, {  "reps": "15", "rest" : "45" } ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "low-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=Vxlf9_eE1JI", location: ["gym", "home"], levels: ["superset","low" ], gender: ["male", "female"], name: "Swim Kicks", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "25", "rest" : "45" }, {  "reps": "35", "rest" : "45" }, {  "reps": "35", "rest" : "45" }, {  "reps": "25", "rest" : "45" } ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "low-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=b9vxCkQNBxM", location: ["gym", "home"], levels: ["superset","low" ], gender: ["male", "female"], name: "Resistance Band Good Mornings", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "25", "rest" : "45" }, {  "reps": "35", "rest" : "45" }, {  "reps": "35", "rest" : "45" }, {  "reps": "25", "rest" : "45" } ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "low-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=5Xj6XUa77qc", location: ["gym"], levels: ["superset","low", "medium", "high" ], gender: ["male", "female"], name: "Barbell Good Mornings", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45" } ], "medium": [ {  "reps": "12", "rest" : "35" }, {  "reps": "10", "rest" : "35" }, {  "reps": "10", "rest" : "45" }, {  "reps": "12", "rest" : "60" } ], "high": [ {  "reps": "12", "rest" : "35" }, {  "reps": "10", "rest" : "35" }, {  "reps": "10", "rest" : "45" }, {  "reps": "12", "rest" : "50" }, {  "reps": "12", "rest" : "60" } ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "low-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=jh45myksaEs&t=2s", location: ["gym"], levels: ["superset","low", "medium", "high" ], gender: ["male", "female"], name: "Back Extension", sets: '+"'"+ ' { "superset": [ {  "reps": "15", "rest" : "0"  } ], "low": [ {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45" }, {  "reps": "12", "rest" : "45" } ], "medium": [ {  "reps": "12", "rest" : "35" }, {  "reps": "10", "rest" : "35" }, {  "reps": "10", "rest" : "45" }, {  "reps": "12", "rest" : "60" } ], "high": [ {  "reps": "12", "rest" : "35" }, {  "reps": "10", "rest" : "35" }, {  "reps": "10", "rest" : "45" }, {  "reps": "12", "rest" : "50" }, {  "reps": "12", "rest" : "60" } ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "low-back" }, '+
									'{ VideoURL:"https://www.youtube.com/watch?v=pAplQXk3dkU", location: ["gym"], levels: ["superset","low" ], gender: ["male", "female"], name: "Cable Wood Chopper", sets: '+"'"+ ' { "superset": [ {  "reps": "20", "rest" : "0"  } ], "low": [ {  "reps": "20", "rest" : "45" }, {  "reps": "20", "rest" : "45" }, {  "reps": "20", "rest" : "45" } ] }'+"'"+', uuid:'+ JSON.stringify(uuidV4())+', description: "", part:"back", detailed_part: "low-back" } '+
//END OF BACK							
"]";




export const frameworks = "["+
						 "{gender: 'female', part: 'core', goal: 'Smaller'}, "+
						 "{gender: 'female', part: 'core', goal: 'Tone'}, "+
						 //"{gender: 'female', part: 'core', goal: 'Bigger'}, "+
						 "{gender: 'male', part: 'core', goal: 'Smaller'}, "+
						 "{gender: 'male', part: 'core', goal: 'Tone'}, "+
						 //"{gender: 'male', part: 'core', goal: 'Bigger'}, "+
						 "{gender: 'female', part: 'glutes', goal: 'Smaller'}, "+
						 "{gender: 'female', part: 'glutes', goal: 'Tone'}, "+
						 "{gender: 'female', part: 'glutes', goal: 'Bigger'}, "+
						 "{gender: 'male', part: 'glutes', goal: 'Smaller'}, "+
						 "{gender: 'male', part: 'glutes', goal: 'Tone'}, "+
						 "{gender: 'male', part: 'glutes', goal: 'Bigger'}, "+
						 "{gender: 'female', part: 'back', goal: 'Smaller'}, "+
						 "{gender: 'female', part: 'back', goal: 'Tone'}, "+
						 "{gender: 'female', part: 'back', goal: 'Bigger'}, "+
						 "{gender: 'male', part: 'back', goal: 'Smaller'}, "+
						 "{gender: 'male', part: 'back', goal: 'Tone'}, "+
						 "{gender: 'male', part: 'back', goal: 'Bigger'}, "+
						 "{gender: 'female', part: 'hamstrings', goal: 'Smaller'}, "+
						 "{gender: 'female', part: 'hamstrings', goal: 'Tone'}, "+
						 "{gender: 'female', part: 'hamstrings', goal: 'Bigger'}, "+
						 "{gender: 'male', part: 'hamstrings', goal: 'Smaller'}, "+
						 "{gender: 'male', part: 'hamstrings', goal: 'Tone'}, "+
						 "{gender: 'male', part: 'hamstrings', goal: 'Bigger'}, "+
						 "{gender: 'female', part: 'calves', goal: 'Smaller'}, "+
						 "{gender: 'female', part: 'calves', goal: 'Tone'}, "+
						 "{gender: 'female', part: 'calves', goal: 'Bigger'}, "+
						 "{gender: 'male', part: 'calves', goal: 'Smaller'}, "+
						 "{gender: 'male', part: 'calves', goal: 'Tone'}, "+
						 "{gender: 'male', part: 'calves', goal: 'Bigger'}, "+
						 "{gender: 'female', part: 'biceps', goal: 'Smaller'}, "+
						 "{gender: 'female', part: 'biceps', goal: 'Tone'}, "+
						 "{gender: 'female', part: 'biceps', goal: 'Bigger'}, "+
						 "{gender: 'male', part: 'biceps', goal: 'Smaller'}, "+
						 "{gender: 'male', part: 'biceps', goal: 'Tone'}, "+
						 "{gender: 'male', part: 'biceps', goal: 'Bigger'}, "+
						 "{gender: 'female', part: 'quads', goal: 'Smaller'}, "+
						 "{gender: 'female', part: 'quads', goal: 'Tone'}, "+
						 "{gender: 'female', part: 'quads', goal: 'Bigger'}, "+
						 "{gender: 'male', part: 'quads', goal: 'Smaller'}, "+
						 "{gender: 'male', part: 'quads', goal: 'Tone'}, "+
						 "{gender: 'male', part: 'quads', goal: 'Bigger'}, "+
						 "{gender: 'female', part: 'triceps', goal: 'Smaller'}, "+
						 "{gender: 'female', part: 'triceps', goal: 'Tone'}, "+
						 "{gender: 'female', part: 'triceps', goal: 'Bigger'}, "+
						 "{gender: 'male', part: 'triceps', goal: 'Smaller'}, "+
						 "{gender: 'male', part: 'triceps', goal: 'Tone'}, "+
						 "{gender: 'male', part: 'triceps', goal: 'Bigger'}, "+
						 "{gender: 'female', part: 'shoulders', goal: 'Smaller'}, "+
						 "{gender: 'female', part: 'shoulders', goal: 'Tone'}, "+
						 "{gender: 'female', part: 'shoulders', goal: 'Bigger'}, "+
						 "{gender: 'male', part: 'shoulders', goal: 'Smaller'}, "+
						 "{gender: 'male', part: 'shoulders', goal: 'Tone'}, "+
						 "{gender: 'male', part: 'shoulders', goal: 'Bigger'}, "+
						 "{gender: 'female', part: 'chest', goal: 'Smaller'}, "+
						 "{gender: 'female', part: 'chest', goal: 'Tone'}, "+
						 "{gender: 'female', part: 'chest', goal: 'Bigger'}, "+
						 "{gender: 'male', part: 'chest', goal: 'Smaller'}, "+
						 "{gender: 'male', part: 'chest', goal: 'Tone'}, "+
						 "{gender: 'male', part: 'chest', goal: 'Bigger'} "+


"]"

export const patterns = "["+
						 "{soreness: 1, movements: ['high','high', 'high'], part: 'core', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 2, movements: ['high','high'], part: 'core', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 3, movements: ['medium'], part: 'core', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 1, movements: ['high','high', 'high'], part: 'core', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 2, movements: ['high','medium'], part: 'core', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 3, movements: ['medium'], part: 'core', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 1, movements: ['high', 'high'], part: 'core', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 2, movements: ['medium','medium'], part: 'core', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 3, movements: ['low'], part: 'core', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 1, movements: ['high','high'], part: 'core', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 2, movements: ['medium', 'medium'], part: 'core', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 3, movements: ['low'], part: 'core', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 1, movements: ['medium','medium','medium','low'], part: 'glutes', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 2, movements: ['medium','superset','low'], part: 'glutes', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 3, movements: ['medium','medium','low'], part: 'glutes', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 1, movements: ['medium','medium','medium','low'], part: 'glutes', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 2, movements: ['medium','medium','low'], part: 'glutes', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 3, movements: ['medium','medium','low'], part: 'glutes', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 1, movements: ['high','medium','medium','low'], part: 'glutes', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 2, movements: ['high','medium','low'], part: 'glutes', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 3, movements: ['high','low'], part: 'glutes', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 1, movements: ['high','medium','medium','low'], part: 'glutes', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 2, movements: ['high','medium','low'], part: 'glutes', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 3, movements: ['high', 'low'], part: 'glutes', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 1, movements: ['high', 'superset','high','superset', 'medium','low'], part: 'glutes', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 2, movements: ['high', 'superset','medium','superset', 'low','low'], part: 'glutes', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 3, movements: ['high', 'superset','medium','superset', 'low','low'], part: 'glutes', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 1, movements: ['high', 'superset', 'medium','low'], part: 'glutes', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 2, movements: ['high', 'superset','medium','superset', 'low','low'], part: 'glutes', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 3, movements: ['high', 'superset', 'medium','low'], part: 'glutes', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 1, movements: ['medium','low','low','low', 'low'], part: 'back', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 2, movements: ['medium','low','low','low'], part: 'back', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 3, movements: ['medium','low','low'], part: 'back', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 1, movements: ['medium','low','low','low', 'low'], part: 'back', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 2, movements: ['medium','low','low','low'], part: 'back', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 3, movements: ['medium','low','low'], part: 'back', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 1, movements: ['medium', 'superset','medium','medium'], part: 'back', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 2, movements: ['high','medium','medium'], part: 'back', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 3, movements: ['medium','medium','low'], part: 'back', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 1, movements: ['medium', 'superset','medium','medium'], part: 'back', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 2, movements: ['high','medium','medium'], part: 'back', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 3, movements: ['medium','medium','low'], part: 'back', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 1, movements: ['high','superset','high','superset','medium'], part: 'back', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 2, movements: ['high','superset','medium','superset','low'], part: 'back', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 3, movements: ['medium','superset','medium','superset','low'], part: 'back', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 1, movements: ['high','superset','high','superset','low'], part: 'back', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 2, movements: ['high','superset','medium','superset','low'], part: 'back', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 3, movements: ['medium','superset','low','superset','low'], part: 'back', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 1, movements: ['medium','low','low','low'], part: 'hamstrings', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 2, movements: ['low','low','low','low'], part: 'hamstrings', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 3, movements: ['low','low','low'], part: 'hamstrings', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 1, movements: ['medium','low','low','low'], part: 'hamstrings', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 2, movements: ['low','low','low','low'], part: 'hamstrings', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 3, movements: ['low','low'], part: 'hamstrings', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 1, movements: ['high','medium','medium','low'], part: 'hamstrings', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 2, movements: ['medium','medium','low','low'], part: 'hamstrings', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 3, movements: ['medium','low'], part: 'hamstrings', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 1, movements: ['high','medium','medium','low'], part: 'hamstrings', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 2, movements: ['medium','medium','low','low'], part: 'hamstrings', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 3, movements: ['medium','low'], part: 'hamstrings', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 1, movements: ['high','superset','high'], part: 'hamstrings', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 2, movements: ['high','superset','medium'], part: 'hamstrings', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 3, movements: ['high','superset'], part: 'hamstrings', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 1, movements: ['high','superset','high'], part: 'hamstrings', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 2, movements: ['high','superset','medium'], part: 'hamstrings', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 3, movements: ['high','superset'], part: 'hamstrings', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 1, movements: ['medium','low','low'], part: 'calves', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 2, movements: ['low','low','low'], part: 'calves', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 3, movements: ['low','low'], part: 'calves', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 1, movements: ['medium','low','low'], part: 'calves', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 2, movements: ['low','low','low'], part: 'calves', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 3, movements: ['low', 'low'], part: 'calves', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 1, movements: ['medium','medium','low'], part: 'calves', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 2, movements: ['medium','low','low'], part: 'calves', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 3, movements: ['medium','low'], part: 'calves', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 1, movements: ['medium','medium','low'], part: 'calves', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 2, movements: ['medium','low','low'], part: 'calves', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 3, movements: ['medium','low'], part: 'calves', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 1, movements: ['high','superset','medium'], part: 'calves', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 2, movements: ['high','superset'], part: 'calves', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 3, movements: ['high'], part: 'calves', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 1, movements: ['high','superset','low'], part: 'calves', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 2, movements: ['high','superset'], part: 'calves', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 3, movements: ['high'], part: 'calves', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 1, movements: ['medium','low','low'], part: 'biceps', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 2, movements: ['low','low','low'], part: 'biceps', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 3, movements: ['low','low'], part: 'biceps', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 1, movements: ['medium','low','low'], part: 'biceps', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 2, movements: ['low','low','low'], part: 'biceps', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 3, movements: ['low','low'], part: 'biceps', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 1, movements: ['high','medium','medium'], part: 'biceps', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 2, movements: ['high','medium','low'], part: 'biceps', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 3, movements: ['high','low'], part: 'biceps', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 1, movements: ['high','medium','medium'], part: 'biceps', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 2, movements: ['high','medium','low'], part: 'biceps', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 3, movements: ['medium','low'], part: 'biceps', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 1, movements: ['high','superset','high'], part: 'biceps', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 2, movements: ['high','superset','low'], part: 'biceps', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 3, movements: ['medium','superset'], part: 'biceps', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 1, movements: ['high','superset','high'], part: 'biceps', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 2, movements: ['high','superset','low'], part: 'biceps', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 3, movements: ['medium','superset'], part: 'biceps', goal: 'Bigger', gender: 'female'}, "+
						  "{soreness: 1, movements: ['medium','low','low','low'], part: 'quads', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 2, movements: ['low','low','low','low'], part: 'quads', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 3, movements: ['low','low','low'], part: 'quads', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 1, movements: ['medium','low','low','low'], part: 'quads', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 2, movements: ['low','low','low','low'], part: 'quads', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 3, movements: ['low','low','low'], part: 'quads', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 1, movements: ['high','high','medium','medium'], part: 'quads', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 2, movements: ['high','medium','medium','low'], part: 'quads', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 3, movements: ['medium','medium','low'], part: 'quads', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 1, movements: ['high','high','medium','medium'], part: 'quads', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 2, movements: ['high','medium','medium'], part: 'quads', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 3, movements: ['medium','medium','low'], part: 'quads', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 1, movements: ['high','superset','high','superset','low'], part: 'quads', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 2, movements: ['high','superset','medium','superset'], part: 'quads', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 3, movements: ['medium','superset','medium'], part: 'quads', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 1, movements: ['high','superset','high','superset','low'], part: 'quads', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 2, movements: ['high','superset','medium','superset'], part: 'quads', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 3, movements: ['medium','superset','medium'], part: 'quads', goal: 'Bigger', gender: 'female'}, "+
						  "{soreness: 1, movements: ['medium','medium','low'], part: 'triceps', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 2, movements: ['medium','low','low'], part: 'triceps', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 3, movements: ['low','low','low'], part: 'triceps', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 1, movements: ['medium','medium','low'], part: 'triceps', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 2, movements: ['medium','low','low'], part: 'triceps', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 3, movements: ['low','low','low'], part: 'triceps', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 1, movements: ['high','medium','low'], part: 'triceps', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 2, movements: ['high','low','low'], part: 'triceps', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 3, movements: ['high','low'], part: 'triceps', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 1, movements: ['high','medium','low'], part: 'triceps', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 2, movements: ['high','low','low'], part: 'triceps', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 3, movements: ['medium','low'], part: 'triceps', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 1, movements: ['high','superset','medium'], part: 'triceps', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 2, movements: ['high','superset'], part: 'triceps', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 3, movements: ['medium','superset'], part: 'triceps', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 1, movements: ['high','superset','medium'], part: 'triceps', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 2, movements: ['high','superset'], part: 'triceps', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 3, movements: ['medium','superset'], part: 'triceps', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 1, movements: ['medium','low','low'], part: 'shoulders', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 2, movements: ['low','low','low'], part: 'shoulders', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 3, movements: ['low','low'], part: 'shoulders', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 1, movements: ['medium','low','low'], part: 'shoulders', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 2, movements: ['low','low','low'], part: 'shoulders', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 3, movements: ['low','low'], part: 'shoulders', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 1, movements: ['high','medium','low'], part: 'shoulders', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 2, movements: ['high','medium'], part: 'shoulders', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 3, movements: ['medium','medium'], part: 'shoulders', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 1, movements: ['high','medium','low'], part: 'shoulders', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 2, movements: ['high','medium'], part: 'shoulders', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 3, movements: ['medium','medium'], part: 'shoulders', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 1, movements: ['high','superset','high','superset'], part: 'shoulders', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 2, movements: ['high','superset','medium','low'], part: 'shoulders', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 3, movements: ['medium','superset','low'], part: 'shoulders', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 1, movements: ['high','superset','high','superset'], part: 'shoulders', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 2, movements: ['high','superset','medium','low'], part: 'shoulders', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 3, movements: ['medium','superset','low'], part: 'shoulders', goal: 'Bigger', gender: 'female'}, "+
						  "{soreness: 1, movements: ['medium','medium','low'], part: 'chest', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 2, movements: ['medium','low','low'], part: 'chest', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 3, movements: ['medium','low'], part: 'chest', goal: 'Smaller', gender: 'male'}, "+
						 "{soreness: 1, movements: ['medium','medium','low'], part: 'chest', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 2, movements: ['medium','low','low'], part: 'chest', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 3, movements: ['medium','low'], part: 'chest', goal: 'Smaller', gender: 'female'}, "+
						 "{soreness: 1, movements: ['high','medium','medium'], part: 'chest', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 2, movements: ['high','medium','low'], part: 'chest', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 3, movements: ['medium','medium','low'], part: 'chest', goal: 'Tone', gender: 'male'}, "+
						 "{soreness: 1, movements: ['high','medium','medium'], part: 'chest', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 2, movements: ['high','medium','low'], part: 'chest', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 3, movements: ['medium','medium','low'], part: 'chest', goal: 'Tone', gender: 'female'}, "+
						 "{soreness: 1, movements: ['high','superset','high','superset','medium'], part: 'chest', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 2, movements: ['high','superset','high','superset','low'], part: 'chest', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 3, movements: ['medium','superset','medium','superset'], part: 'chest', goal: 'Bigger', gender: 'male'}, "+
						 "{soreness: 1, movements: ['high','superset','high','superset','medium'], part: 'chest', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 2, movements: ['high','superset','high','superset','low'], part: 'chest', goal: 'Bigger', gender: 'female'}, "+
						 "{soreness: 3, movements: ['medium','superset','medium','superset'], part: 'chest', goal: 'Bigger', gender: 'female'} "+
						
"]";

