import jwt from 'jsonwebtoken';
import uuid from 'node-uuid';
const uuidV4 = require('uuid');

export const secret = 'lukeiamyourfather'; 
export const exercises_core_pack = [
	"{ VideoURL:'https://www.youtube.com/watch?v=Q9AlsWFyYE8&feature=youtu.be', location: ['gym', 'home'], levels: ['superset', 'low'], gender: ['male', 'female'], name: 'Plank', sets: '{ 'superset': [ { 'id': 1, 'reps': '30', 'rest' : '0',  } ], 'low': [ { 'id': 1, 'reps': '30', 'rest' : '45' }, { 'id': 2, 'reps': '30', 'rest' : '45' }, { 'id': 3, 'reps': '30', 'rest' : '45'} ] }, uuid:"+ uuidV4() +", 'description': 'Your Hips must not sag. Fight to keep hips in line with the rest of your body. Try putting a PVC pipe or broomstick on your back next time you do a plank. It should touch the top of your tailbone, your upper back and the back of your head. That's how you know you're in a neutral position and performing them correctly.', part:'core', detailed_part: 'abs' }" ,
	"{ VideoURL:'https://youtu.be/N8xOZ9cHHjo', location: ['gym', 'home'], levels: ['superset', 'low'], gender: ['male', 'female'], name: 'Crunch', sets:'{ 'superset': [ { 'id': 1, 'reps': '30', 'rest' : '0' } ], 'low': [ { 'id': 1, 'reps': '30', 'rest' : '45' }, { 'id': 2, 'reps': '30', 'rest' : '45' }, { 'id': 3, 'reps': '30', 'rest' : '45'} ] }, uuid:"+ uuidV4() +", description: 'Do not jerk your weight up. Focus on utilizing your abs to raise your body up and make sure you are moving slowly and deliberately as you perform each crunch. Do not perform a sit up and instead focus on cruching your abs. Do not focus on raising all the way up as you would for a sit up.', part:'core', detailed_part: 'abs' }" ,
	"{ VideoURL:'https://youtu.be/Ot2x2yhV1f0', location: ['gym', 'home'], levels: ['superset', 'low'], gender: ['male', 'female'], name: 'Sit up', sets: '{ 'superset': [ { 'id': 1, 'reps': '30', 'rest' : '0',  } ], 'low': [ { 'id': 1, 'reps': '30', 'rest' : '45' }, { 'id': 2, 'reps': '30', 'rest' : '45' }, { 'id': 3, 'reps': '30', 'rest' : '45'} ] }, uuid:"+ uuidV4() +", 'description': '', part:'core', detailed_part: 'abs'}" ,
	"{ VideoURL:'https://youtu.be/AFBC0HDflWo', name: 'Air Bicycle', location: ['gym', 'home'], levels: ['superset', 'low'], gender: ['male', 'female'], sets: '{ 'superset': [ { 'id': 1, 'reps': '30', 'rest' : '0',  } ], 'low': [ { 'id': 1, 'reps': '30', 'rest' : '45' }, { 'id': 2, 'reps': '30', 'rest' : '45' }, { 'id': 3, 'reps': '30', 'rest' : '45'} ] }, uuid:"+ uuidV4() +", 'description': '', part:'core', detailed_part: 'abs'}" ,
	"{ VideoURL:'https://youtu.be/ZF_fwwd5oxw', name: 'Lying Leg Raise', location: ['gym', 'home'], levels: ['superset', 'low'], gender: ['male', 'female'], sets: '{ 'superset': [ { 'id': 1, 'reps': '30', 'rest' : '0',  } ], 'low': [ { 'id': 1, 'reps': '30', 'rest' : '45' }, { 'id': 2, 'reps': '30', 'rest' : '45' }, { 'id': 3, 'reps': '30', 'rest' : '45'} ] }, uuid:"+ uuidV4() +", 'description': '', part:'core', detailed_part: 'abs'}" ,
	"{ VideoURL:'https://youtu.be/_LiAqnFE5mg', name: 'Ab Plate Twist', location: ['gym', 'home'], levels: ['superset', 'low', 'medium', 'high'], gender: ['male', 'female'], sets: '{ 'superset': [ { 'id': 1, 'reps': '30', 'rest' : '0',  } ], 'low': [ { 'id': 1, 'reps': '30', 'rest' : '45' }, { 'id': 2, 'reps': '30', 'rest' : '45' }, { 'id': 3, 'reps': '30', 'rest' : '45'} ], 'medium': [{ 'id': 1, 'reps': '30', 'rest' : '30' }, { 'id': 2, 'reps': '30', 'rest' : '30' }, { 'id': 3, 'reps': '30', 'rest' : '30'}, { 'id': 4, 'reps': '30', 'rest' : '45'}], 'high': [{ 'id': 1, 'reps': '30', 'rest' : '30' }, { 'id': 2, 'reps': '30', 'rest' : '30' }, { 'id': 3, 'reps': '30', 'rest' : '30'}, { 'id': 4, 'reps': '30', 'rest' : '45'}, { 'id': 4, 'reps': '30', 'rest' : '45'}] }, uuid:"+ uuidV4() +", 'description': '', part:'core', detailed_part: 'abs'}" ,
	"{ VideoURL:'https://youtu.be/G1Xpt8vbVBc', name: 'Mountain Climber', location: ['gym', 'home'], levels: ['superset', 'low'], gender: ['male', 'female'], sets: '{ 'superset': [ { 'id': 1, 'reps': '30', 'rest' : '0',  } ], 'low': [ { 'id': 1, 'reps': '30', 'rest' : '45' }, { 'id': 2, 'reps': '30', 'rest' : '45' }, { 'id': 3, 'reps': '30', 'rest' : '45'} ] }, uuid:"+ uuidV4() +", 'description': '', part:'core', detailed_part: 'abs'}" ,
	"{ VideoURL:'https://youtu.be/VAERCnrM_l8', name: 'Full Hanging Leg Raise', location: ['gym'], levels: ['superset', 'low', 'medium'], gender: ['male', 'female'], sets: '{ 'superset': [ { 'id': 1, 'reps': '30', 'rest' : '0',  } ], 'low': [ { 'id': 1, 'reps': '10', 'rest' : '45' }, { 'id': 2, 'reps': '10', 'rest' : '45' }, { 'id': 3, 'reps': '10', 'rest' : '45'} ], 'medium': [ { 'id': 1, 'reps': '30', 'rest' : '45' }, { 'id': 2, 'reps': '30', 'rest' : '45' }, { 'id': 3, 'reps': '30', 'rest' : '45'} ] }, uuid:"+ uuidV4() +", 'description': '', part:'core', detailed_part: 'abs'}" ,


]